name: snooper
description: "Track your Discord activity and share it with friends."
publish_to: 'none'

version: 1.2.0+8

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  device_info_plus: ^11.3.0
  app_usage: ^4.0.0
  permission_handler: ^11.4.0
  cached_network_image: ^3.4.1
  dynamic_color: ^1.7.0
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  intl: ^0.20.2
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  installed_apps: ^1.5.2
  path_provider: ^2.1.5
  file_picker: ^9.0.2
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/onboard/
    - assets/branding/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package